### ISSUE TITLE
uninitialized constant RuboCop::Cop::RSpec::RSpecとなる

### ISSUE THREAD

**Issue by mom0tomo** [ryz310/rubocop_challenger#249]
v2.0.0.pre8で下記のようなエラーが発生しました。
```
bundle install
bundle exec rubocop_challenger go \
  --email=xxxxxxxxxxxx \
  --name="Rubocop Challenger"

...中略

$ GIT_AUTHOR_NAME="Rubocop Challenger" GIT_AUTHOR_EMAIL="xxxxxxxxxxxx" GIT_COMMITTER_NAME="Rubocop Challenger" GIT_COMMITTER_EMAIL="xxxxxxxxxxxx" git commit -m ":police_car: regenerate rubocop todo"
[rubocop-challenge/20190814000431 7ced4aa0d] :police_car: regenerate rubocop todo
 1 file changed, 2 insertions(+), 3 deletions(-)
uninitialized constant RuboCop::Cop::RSpec::RSpec
Exited with code 1
```
#237 と同じものがv2.0.0.pre8でも発生しているようです。
ご確認いただけると助かります 🙏

**Comment by ryz310** [comment]
@mom0tomo 
ご報告ありがとうございます 👍 

ご利用中の rubocop-rspec のバージョンってわかりますか？
もし分かれば教えて頂けると助かります 🙏

**Comment by mom0tomo** [comment]
> rubocop-rspec (1.35.0)
です！

**Comment by ryz310** [comment]
バージョン報告ありがとうございます 👍 
調査して対応します 🙏

**Comment by ryz310** [comment]
@mom0tomo 
#252 にて `v2.0.0.pre9` をリリースしました 🙏 

残念ながら上記のバグは修正できていないのですが、RubocopChallenge の PR は作成されるようになったはずです。恐らくですが、PR の 0 コメを作成する際にエラーになっているものの、Rubocop Challenge そのものは成功していると思われます。

実は RubocopChallenger の 0 コメの作成は、 RuboCop のソースコードそのものから YARD を読み込んで、[Rubydoc.info](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/DuplicatedGem) と同じようなドキュメントを生成しているのですが、これは RuboCop 実装に依存するため、RuboCop 関連の gem が更新されると動かなくなるケースが結構多く、どのルールが影響しているのかが分からないと対応が難しいのです。。

今回の対応では、 0 コメの作成に失敗した場合でも異常終了させず、 0 コメは作成できないけど PR だけは作成する、という方式に変えてみました。ファイルの変更差分から、どのようなルールが修正されたのかは分かると思います。また、その PR にエラー情報が含まれるようになるので、お手数ですが改めてエラー情報を共有して頂けると助かります 🙇

**Comment by mom0tomo** [comment]
お返事遅くなりましてすみません！
リリースいただきありがとうございます。改めて実行し、エラーが出た場合に情報を共有いたします。

**Comment by ryz310** [comment]
@mom0tomo 
はい！宜しくお願いします！

**Comment by mom0tomo** [comment]
下記のエラー情報がPRにプリントされるようになりました！
```
title: RSpec/EmptyLineAfterExample
message: uninitialized constant RuboCop::Cop::RSpec::RSpec

---
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/rubocop/yardoc.rb:46:in `const_get'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/rubocop/yardoc.rb:46:in `rescue in find_cop_class'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/rubocop/yardoc.rb:43:in `find_cop_class'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/rubocop/yardoc.rb:9:in `initialize'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/github/pr_template.rb:57:in `new'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/github/pr_template.rb:57:in `yardoc'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/github/pr_template.rb:49:in `description'
(erb):9:in `generate'
/usr/local/lib/ruby/2.6.0/erb.rb:901:in `eval'
/usr/local/lib/ruby/2.6.0/erb.rb:901:in `result'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/github/pr_template.rb:17:in `generate'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/pull_request.rb:57:in `create_rubocop_challenge_pr!'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/go.rb:122:in `create_pull_request!'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/go.rb:43:in `exec'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/lib/rubocop_challenger/cli.rb:65:in `go'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre9/exe/rubocop_challenger:6:in `<top (required)>'
/usr/local/bundle/bin/rubocop_challenger:23:in `load'
/usr/local/bundle/bin/rubocop_challenger:23:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by ryz310** [comment]
@mom0tomo 
おお！ありがとうございます！ :sparkles:
ちなみに作成された PR  は RubocopChallenge された状態で出来たがっていたと思いますが、どうでしたかね？
ご報告頂いたエラーの件の対応もなる早で行いますが、もし PR の中身が正しいようならば、そちらの PR は merge してもらっても良いかと思います 🙏

**Comment by mom0tomo** [comment]
はい、その通りです！RubocopChallenge された状態でPRが上がりました。ありがとうございます、こちらはmergeします。

**Comment by ryz310** [comment]
#238 で以下のように rspec 関連の gem の loading の順序を変えたが、思ったように動いていなかったようだ 🙄 

**Before**

1. Load rspec related gems
2. Update rspec related gems
3. Rubocop Challenge

**After**

1. Update rspec related gems
2. Rubocop Challenge
3. Load rspec related gems

実行中の Ruby Script から `gem update` を実行して `require` した時に、最新の gem が load 出来るのかどうかを改めて調べたほうが良さそう。

**Comment by ryz310** [comment]
会社にも同じ PR 来てたけど、こっちは上手く動いてたな。。 🤔 

https://github.com/feedforce/social-plus/pull/3593

![スクリーンショット 2019-10-17 18 07 35](https://user-images.githubusercontent.com/3985540/66994941-1886d500-f109-11e9-9150-8c31a115b59d.png)

Gemfile.lock
```diff
-    rubocop (0.74.0)
+    rubocop (0.75.0)
...
-    rubocop-rspec (1.35.0)
-      rubocop (>= 0.60.0)
+    rubocop-rspec (1.36.0)
+      rubocop (>= 0.68.1)
```

**Comment by ryz310** [comment]
@mom0tomo 

何度もメンションすみません、お手すきでコメント頂けたら幸いです 🙏 

https://github.com/ryz310/rubocop_challenger/issues/249#issuecomment-543082163 にもコメントしたのですが、自分の環境だと `RSpec/EmptyLineAfterExample` の Rubocop Challenge が動いていたので、インストール方法や環境依存で動かなくなるのではないか、と考えています。

@mom0tomo さんの `rubocop_challenger` のインストール方法の方法について質問なのですが、 `Gemfile` で `rubocop_challenger` を管理されていたりはしないでしょうか？もしそうであれば、以下のように Circle CI の実行時に都度インストールする方法に変えると動作するようになるかもしれません。

```yml
jobs:
  rubocop_challenge:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Rubocop Challenge
          command: |
            gem install rubocop_challenger --pre # (ここでインストールしています)
            rubocop_challenger go \
              --email=rubocop-challenger@example.com \
              --name="Rubocop Challenger"
```

**Comment by mom0tomo** [comment]
ご指摘の通り `Gemfile`でインストールを行なっていました。
なるほど、今後CircleCiの実行時に都度インストールするようにしてみます！

**Comment by ryz310** [comment]
@mom0tomo 
宜しくです！また不具合がありましたらご報告ください 🙏 
いったんこちらの Issue は close とさせて頂きます ✅
