### ISSUE TITLE
Description of `Rails/IndexBy` PR has broken

### ISSUE THREAD

**Issue by ryz310** [ryz310/rubocop_challenger#302]
**Describe the bug**
Description of `Rails/IndexBy` PR has broken.

**Error information**
```
title: Rails/IndexBy
message: uninitialized constant RuboCop::Cop::RSpec::Rails

---
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/rubocop/yardoc.rb:46:in `const_get'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/rubocop/yardoc.rb:46:in `rescue in find_cop_class'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/rubocop/yardoc.rb:43:in `find_cop_class'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/rubocop/yardoc.rb:9:in `initialize'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/github/pr_template.rb:57:in `new'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/github/pr_template.rb:57:in `yardoc'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/github/pr_template.rb:49:in `description'
(erb):9:in `generate'
/usr/lib64/ruby/2.4.0/erb.rb:896:in `eval'
/usr/lib64/ruby/2.4.0/erb.rb:896:in `result'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/github/pr_template.rb:17:in `generate'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/pull_request.rb:57:in `create_rubocop_challenge_pr!'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/go.rb:122:in `create_pull_request!'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/go.rb:43:in `exec'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/lib/rubocop_challenger/cli.rb:65:in `go'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/rubocop_challenger-2.0.0.pre10/exe/rubocop_challenger:6:in `<top (required)>'
/usr/local/bundle/bin/rubocop_challenger:23:in `load'
/usr/local/bundle/bin/rubocop_challenger:23:in `<main>'
```

**RubocopChallenger version (please complete the following information):**
 - 2.0.0.pre10

**RuboCop versions (please complete the following information):**
 - rubocop: 0.80.1
 - rubocop-rails: 2.5.0

**Comment by ryz310** [comment]
It is wrong to refer to the constant `RuboCop::Cop::RSpec::Rails`. The correct one is `RuboCop::Cop::Rails`.

**Comment by ryz310** [comment]
The document URL `https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/IndexBy` is wrong too. The correct one is `https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/IndexBy`.

:x: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/IndexBy
:o: https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/IndexBy
