### ISSUE TITLE
Fail to describe Rails/ApplicationRecord

### ISSUE THREAD

**Issue by ryz310** [ryz310/rubocop_challenger#440]
**Describe the bug**

**Error information**
Add error message and backtrace if you can see.

```
title: Rails/ApplicationRecord
message: undefined method `docstring' for nil:NilClass

---
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/rubocop/yardoc.rb:16:in `description'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/github/pr_template.rb:49:in `description'
(erb):9:in `generate'
/usr/local/lib/ruby/2.5.0/erb.rb:876:in `eval'
/usr/local/lib/ruby/2.5.0/erb.rb:876:in `result'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/github/pr_template.rb:17:in `generate'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/pull_request.rb:57:in `create_rubocop_challenge_pr!'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/go.rb:107:in `create_pull_request!'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/go.rb:43:in `exec'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/lib/rubocop_challenger/cli.rb:70:in `go'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/rubocop_challenger-2.0.1/exe/rubocop_challenger:6:in `<top (required)>'
/usr/local/bundle/bin/rubocop_challenger:23:in `load'
/usr/local/bundle/bin/rubocop_challenger:23:in `<main>'
```

**RubocopChallenger version (please complete the following information):**
 - [e.g. 1.2.3]

**RuboCop versions (please complete the following information):**
 - rubocop: [e.g. 1.2.3]
 - rubocop-performance: [e.g. 1.2.3]
 - rubocop-rails: [e.g. 1.2.3]
 - rubocop-rspec: [e.g. 1.2.3]

**Additional context**

**Comment by ryz310** [comment]
I found cause of the problem.

The Cop of  "Rails/ApplicationRecord" has no instance method without inherit, so finding source location was faild to use "Method#source_location":
<img width="874" alt="スクリーンショット 2021-01-08 0 41 16" src="https://user-images.githubusercontent.com/3985540/103913679-2bd9f200-514c-11eb-80a2-384842e69b03.png">

In normally, that approach is fine:
<img width="874" alt="スクリーンショット 2021-01-08 0 37 43" src="https://user-images.githubusercontent.com/3985540/103913563-04832500-514c-11eb-8511-50ce204495a1.png">

I cannot resolve this problem completely, but can resolve it after Ruby 2.7 with Module#const_source_location:
<img width="824" alt="スクリーンショット 2021-01-08 0 45 28" src="https://user-images.githubusercontent.com/3985540/103914169-c5090880-514c-11eb-85ae-6e8b729b440f.png">
