### ISSUE TITLE
Failed to create the cop description: Gemspec/RequireMFA

### ISSUE THREAD

**Issue by ryz310** [ryz310/rubocop_challenger#545]
**Describe the bug**
Failed to create the cop description.

**Error information**

```
title: Gemspec/RequireMFA
message: uninitialized constant RuboCop::Cop::RSpec::Gemspec
Did you mean?  RuboCop::Cop::Gemspec

---
/home/circleci/repo/lib/rubocop_challenger/rubocop/yardoc.rb:51:in `const_get'
/home/circleci/repo/lib/rubocop_challenger/rubocop/yardoc.rb:51:in `rescue in find_cop_class'
/home/circleci/repo/lib/rubocop_challenger/rubocop/yardoc.rb:48:in `find_cop_class'
/home/circleci/repo/lib/rubocop_challenger/rubocop/yardoc.rb:9:in `initialize'
/home/circleci/repo/lib/rubocop_challenger/github/pr_template.rb:61:in `new'
/home/circleci/repo/lib/rubocop_challenger/github/pr_template.rb:61:in `yardoc'
/home/circleci/repo/lib/rubocop_challenger/github/pr_template.rb:57:in `safe_autocorrect?'
(erb):5:in `generate'
/usr/local/lib/ruby/3.0.0/erb.rb:905:in `eval'
/usr/local/lib/ruby/3.0.0/erb.rb:905:in `result'
/home/circleci/repo/lib/rubocop_challenger/github/pr_template.rb:17:in `generate'
/home/circleci/repo/lib/rubocop_challenger/pull_request.rb:60:in `create_rubocop_challenge_pr!'
/home/circleci/repo/lib/rubocop_challenger/go.rb:109:in `create_pull_request!'
/home/circleci/repo/lib/rubocop_challenger/go.rb:45:in `exec'
/home/circleci/repo/lib/rubocop_challenger/cli.rb:74:in `go'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
/home/circleci/repo/exe/rubocop_challenger:6:in `<top (required)>'
/usr/local/bundle/bin/rubocop_challenger:23:in `load'
/usr/local/bundle/bin/rubocop_challenger:23:in `<top (required)>'
/usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
/usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
/usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
/usr/local/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
/usr/local/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**RubocopChallenger version (please complete the following information):**
 - [e.g. 1.2.3]

**RuboCop versions (please complete the following information):**
 - rubocop: 1.23.0
 - rubocop-rspec: 2.6.0
 - rubocop-ast 1.13.0

**Additional context**

**Comment by ryz310** [comment]
Already fixed
