### ISSUE TITLE
message: uninitialized constant RuboCop::Cop::RSpec::RSpec

### ISSUE THREAD

**Issue by mathieujobin** [ryz310/rubocop_challenger#652]
**Describe the bug**
last PR did not have description, due to error, reporting as requested.

**Error information**
# Rubocop challenge!

[RSpec/Rails/HaveHttpStatus](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/Rails/HaveHttpStatus)

## Description

Failed to create the cop description.
Please report bugs [here](https://github.com/ryz310/rubocop_challenger/issues/new?assignees=ryz310&labels=bug&template=bug_report.md) with following error information.

```
title: RSpec/Rails/HaveHttpStatus
message: uninitialized constant RuboCop::Cop::RSpec::RSpec
Did you mean?  RuboCop::RSpec

---
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/rubocop/yardoc.rb:51:in `const_get'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/rubocop/yardoc.rb:51:in `rescue in find_cop_class'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/rubocop/yardoc.rb:48:in `find_cop_class'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/rubocop/yardoc.rb:9:in `initialize'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/github/pr_template.rb:61:in `new'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/github/pr_template.rb:61:in `yardoc'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/github/pr_template.rb:57:in `safe_autocorrect?'
(erb):5:in `generate'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/erb.rb:905:in `eval'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/2.7.0/erb.rb:905:in `result'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/github/pr_template.rb:17:in `generate'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/pull_request.rb:60:in `create_rubocop_challenge_pr!'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/go.rb:111:in `create_pull_request!'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/go.rb:47:in `exec'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/lib/rubocop_challenger/cli.rb:78:in `go'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/rubocop_challenger-2.9.0/exe/rubocop_challenger:6:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/rubocop_challenger:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/rubocop_challenger:23:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli/exec.rb:23:in `run'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli.rb:483:in `exec'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli.rb:31:in `dispatch'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/cli.rb:25:in `start'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:48:in `block in <top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.17/exe/bundle:36:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
```

Auto generated by [rubocop_challenger](https://github.com/ryz310/rubocop_challenger)

**RubocopChallenger version (please complete the following information):**
2.9.0
**RuboCop versions (please complete the following information):**
```
$ grep "rubocop.*([0-9]" Gemfile.lock 
    rubocop (1.36.0)
    rubocop-ast (1.21.0)
    rubocop-performance (1.15.0)
    rubocop-rails (2.16.0)
    rubocop-rake (0.6.0)
    rubocop-rspec (2.13.1)
    rubocop-thread_safety (0.4.4)
    rubocop_challenger (2.9.0)
```

**Additional context**

**Comment by ryz310** [comment]
@mathieujobin Thank you for your report! I will investigate!
